title: Dash Page Settings
subtitle: Dash Page Settings
body: Dash Page Settings
# content: >
#   <a href="http://" target="_blank" rel="noopener noreferrer">Link</a>
# css-links:
#   - https://cdn.jsdelivr.net/npm/@tabler/core@latest/dist/css/tabler.min.css
# js-links:
#   - https://cdn.jsdelivr.net/npm/@tabler/core@latest/dist/js/tabler.min.js
# script: >
#   <script>
#     alert("Hello World");
#   </script>
content: |
  $title = 'System Settings';
  $links = [];
