<?php
return [
    'Starter',
    'Coming Soon Simple',
    'Coming Soon Countdown',
    'Coming Soon Subscribe',
    'Coming Soon Subscribe Multiple Options',
    'Site Down Simple',
    'Site Down with Estimate Online Information',
    'Site Down Simple with Status Checkers',
    'Choose Profile',
    'Login Success',
    'Logout Success',
    'Pitch Slides',
    'Pitch Body',
    'Pitch Final Slide',
    'Pitch Further Reading',
    'Pitch Slide Full Screen',
    'Pitch Slide Further Reading Links',
    'Dashboard Admin Manual',
    'Dashboard Admin Manual Pages',
    'Dashboard Admin Manual Page',
    'User Flows',
    'User Flow',
    'Screenshot Gallery',
    'Transation Export',
    'Table Sales Order',
    'Table Admin Logs',
    'Table Transations',

    'New Sales Order Approve',
    'New Sales Order No Internet',
    'New Sales Order Approve Error',
    'There is no New Sales Order',
    'New Sales Order Sweet Alert Rate Limit',
    'New Sales Order Sweet Read Admin Log',
    'New Sales Order Sweet Already Approved by Admin',
    'New Sales Order Sweet Other Admin Activities',
    'New Sales Order Sweet Alert Connection Error',
    'New Sales Order Sweet Alert Back Online',
    'New Sales Order Sweet Alert No Internet Connection',
    'New Sales Order Sweet Alert Skeletons',
    'New Sales Order Sweet Alert Pre Loading',
    'Page Not Found',
    'Login Require',

    'Settings',
    'App Setting',
    'Admin Profiles',
    'Admin Profile',
    'Admin Profile Setting',
    'Admin Profile Setting',
    'My Profile',
    'My Profile Setting',
    'Logout',

    'Playgrounds',
    'Send Widgets',
    'Send Email Notifications',
    'Seed Sales Orders',
];




